### ISSUE TITLE
use case

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#1]
Добавил все что есть на данный момент в Doss/Doss/Docs

**Comment by wldmr-key** [comment]
Уместнее в Issue (задаче) размещать ссылку на интересующий [объект](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B5%20%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8.docx?raw=true) . Я сделал это в комментарии, но, правильнее делать это в формулировке задачи

**Comment by wldmr-key** [comment]
Теперь по существу
а) оформление. Use-Case это важный документ и для себя, и для команды. Поэтому, прикинь насколько окупается введение в нем удобной навигации (гиперссылки между сценариями и содержание (автоматическое, разумеется)
б) сценарии вполне толковые
в) сценарий "Отображение границ санитарно-защитной зоны". Противоречие определению ССЗ - разве она считается от границ участка? На мой взгляд, от контура предприятия (сооружения). Грубая аппроксимация - круг от центра расположения предприятия. Пользователю (перед началом проектирования) резоннее вводить не размер ССЗ, а класс объекта.
г) не отсек принципиальной разницы между формированием отчета системой и пользователем

_Раз, уж, ты упомянул их в этом документе... XML-файлы - это не документация по проекту, а примеры. Лучше их хранить в отдельной папке Samples, а еще лучше в ее подпапке (равно, как и примеры запросов к API и т.д.)_

**Comment by Lakovshchikov** [comment]
@wldmr-key [Новая версия use case](https://github.com/Lakovshchikov/DoSS/raw/master/Doss/Doss/Docs/%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B5%20%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8.docx). Комментарии в документе забыл удалить. Что касается границ от участка, или от объекта. При предпроектных проработках размещения пром. объекта (до разработки самого проекта объекта) берется для отсчета граница участка. Я еще в описании предметной области сделал выдержку из санпина. п.3.3. Если делать проект предприятия и в нем защищать СЗЗ, то действительно надо путем анализа характеристик выброса рассчитывать границы и  устанавливать от здания. Но, когда это  только поиск свободных земель - то берется граница участка.
Границы лучше вводить руками, потому что они могут рассчитываться индивидуально.

**Comment by wldmr-key** [comment]
Ок, неплохо. Твой подход =к определению СЗЗ несколько усложняет задачу, но опять-таки не приводит к неминуемости вектора. Быть может, достаточно простого масштабирования растра
