### ISSUE TITLE
Постановка задачи проектирования

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#10]
Не особо понимаю этот пункт. Вот что написано в методичке:_"Постановка задачи проектирования конкретизирует средство достижения цели курсовой работы"_.
Если цель моей работы: "Разработать программную систему для предпроектной проработки...", то средствами для достижения цели являются инструменты и среда разработки? То есть, в данном пункте описать инструменты и среду разработки? Но есть же пункт в РПЗ: _"Обоснование выбора инструментов и платформы для разработки"_.

**Comment by wldmr-key** [comment]
Ох! Опять все с ного на голову!
Цель твоей работы - сделать предпроектную проработку легкой, приятной и необременительной. А, вот, разрабатываемая программная система (и, заодно, изменение технологического процесса проработки) - это средство. В этом пункте - краткое описание того, что нужно сделать (запрограммировать, если угодно) для достижения цели

**Comment by Lakovshchikov** [comment]
@wldmr-key [Постановка задачи проектирования](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9F%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0%20%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8%20%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F.docx)
