### ISSUE TITLE
Внедрение Google Maps или аналога

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#11]
@wldmr-key Что я понял/узнал на данный момент:

1. Добавлять карты google в WPF можно только через элемент WebBrowser. Формировать какую карту вывести можно через App.config. Но просто наложить слоем кадастровую карту встроенную в элемент WebBrowser не получается. Можно было бы наложить поверх и как-то их синхронизировать. Тут возникает проблема. Не получается сделать фон у карты прозрачным, не у самой картинки, а у элемента MapView от arcgis, который отвечает за отображение карты. Свойство Opacity у Background только для чтения. Выглядит это в итоге [вот так](https://drive.google.com/file/d/1CbWb8HwPvlQNPQs1KXrAtS49E-8vdXBb/view?usp=sharing). Серый фон убрать не могу.

2. Бинг предоставляет карты, такого же качества как и arcgis.

3. Вариант, когда мы работает только с картой, а потом отображаем поверх картинку кадастрового деления не подходит. Из соображений функционала. Например: нашли участок по кадастровому номеру, показали его пользователю на карте, отобразили в нужном масштабе кадастровую карту. Вдруг, ему захотелось посмотреть как далеко расположена дорога от этого участка, а она расположена далеко и не влезла в рабочую область вместе с участком. Пользователь начинает увеличивать масштаб, двигать карту, кадастровая карта исчезает, ориентироваться становится сложно. Не удобно. Если только сделать так, что при фиксации рабочей области например на 2 секунды, отправляется запрос на получение кадастровой карты в этих масштабах и координатах? Не представляю на сколько это возможно при реализации.

4. Наверное можно было бы попытаться перейти на web-версию системы, благо api у google maps есть и у arcgis все хорошо с этим. Но, помимо того, что я ни разу не сталкивался ни с верстой сайтов, ни с JS, мне кажется при простом наложении элементов карт от arcgis и google у меня будут те же проблемы, что и в WPF. Тогда пройдется наверное делать потайловый аналог, как у ПКК. Время ограничено, нужно сделать до 1 декабря, и я очень сомневаюсь что разберусь во всем и успею.

5. В пятницу пара по "Техн. интернет". Спрошу Уколова, мб что-то подскажет, посоветует.

Итог: на данный момент вижу 2 возможных решения. Первое - то что я описал в п.3. Скажите насколько это возможно, и с какими трудностями могу столкнуться на первый взгляд. Второе - делать с тем набором карт, что предоставляет arcgis. Теперь мне кажется, что они не такие уж и старые и вполне нормального качества. Выглядят они вот [так](https://www.bing.com/maps).

**Comment by wldmr-key** [comment]
честно говоря я не очень понимаю твои трудности с наложением карт. В аттачменте два примера - один с честным наложением на гугл настоящего участка, другой - с наложением на эту же карту фуфельной кадастровой сетки (лень было привязывать к координатам). Возьми эти файлы на свой диск и подсунь своему элементу вебброузер. Уверен, он их нормально покажет
Если поменять контент (dom) этих статических файлов - вебброузер их перерисует

Я бы конечно, делал это через веб-приложение, но и десктопное, думаю, справится

[tests.zip](https://github.com/Lakovshchikov/DoSS/files/2448259/tests.zip)
