### ISSUE TITLE
Отчет за прошедшее время

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#12]
За неделю сделал следующее:
1) Работает выбор карт, с сохранением точки и масштаба рабочей области
2) Изображение ЗУ накладывается на карту. Не в image. Все взаимодействия с картой не мешают отображению земельного участка. При изменении масштаба он перерисовывается.
3) Поправил все атрибуты, добавил площадь ЗУ. Все пары ключ-значение берутся из сервисов росреестра.

Сейчас работаю над границей СЗЗ. Оказалось все не так просто, как обычно. Если брать картинку земельного участка и масштабировать ее, то граница получается неверная. Пока думаю делать как-то так:
1) Брать картинку земельного участка, когда он отрисован полностью. (если масштаб больше и участок не влезает в экран, то говорить об этом пользователю и предлагать изменить масштаб).
2) Рассчитать площадь одного пикселя, поделив площадь участка на их количество в рисунке.
3) Считая пиксель квадратом, найти длину его стороны.
4) Рассчитать сколько пикселей необходимо на отрисовку СЗЗ в данном масштабе
5) Нарисовать контур СЗЗ.
* Вместо пунктов 1-3 для расчета масштаба можно использовать карту. Брать 2 пикселя соседних и находить расстояние между ними. Это проще и я знаю как это сделать.

Сразу нашел несколько проблем в моем алгоритме:
1) Нужно будет перенести как-то рисунок с участом который я получаю из росреестра на рисунок к примеру 10000х10000 пикселей, что бы хватило места на границы. Почти уверен, что это можно сделать, просто не знаю пока как.
2) Как поступать с отрисовкой границ СЗЗ в местах, где крайние точки. Не знаю как объяснить, приложил рисунок. Представим, что это рисунок, ризбитый попиксельно. Синие квадраты - это участок, красные - СЗЗ. Я не знаю как получить точки на дугах. Можно идти по диагоналям. Но нужно в итоге получить замкнутый контур. В общем, тут могут быть сложности.
![fdtuanvkq0e](https://user-images.githubusercontent.com/43318877/47268165-1b7ed200-d556-11e8-9d97-776e9736beaf.jpg)

**Comment by wldmr-key** [comment]
вроде все сегодня обсудили, да?

**Comment by Lakovshchikov** [comment]
@wldmr-key да, вопросов пока нет

**Comment by Lakovshchikov** [comment]
@wldmr-key сделал нормально границы СЗЗ. Есть вопросы по тому, как узнавать об участках, которые они пересекают. Завтра покажу
