### ISSUE TITLE
Работа с запросами v.2

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#13]
@wldmr-key , периодически вылетает такая ошибка, при любом запросе:
_Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 195.161.118.20:443_
 Например при получении данных о формах земельного участка или запросе картинки ЗУ.  В любом месте, причинно-следственной связи не нахожу. Перезапускаю проект и может все заработать, а может и в другом запросе выкинуть ошибку. С чем может быть связано?

**Comment by wldmr-key** [comment]
скорее всего, у умельцев криво настроен wcf - обрабатывай ошибку и перезапрашивай
