### ISSUE TITLE
Поиск участков в СЗЗ

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#14]
@wldmr-key Я тут поигрался с пикселями, получилась чб картинка ПКК, наложенная на участок и границу СЗЗ. Все вроде классно, но что делать если возникнет следующая ситуация:

1.  Я выбрал незакрашенную точку в границах свой СЗЗ.
2.  Это оказался не участок, а пустое место, кадастровый квартал к примеру.

3.  При закрашивании этой области я могу зайти на участок, если его граница была разорвана надписью.

Что получается я приложил. Как вариант мб перенести границы белого контура надписей? И запрашивать там тоже, если участок, то он накроет нужную часть, если нет - то закрасить внутри контура? Хотя вообще результат пока немного корявый, надеюсь при наложении участков
 пиксели встанут на свои места и все "некорректные" места исчезнут
![img12](https://user-images.githubusercontent.com/43318877/47673711-7ce21900-dbc6-11e8-90f0-661d234b4b10.png)
![default](https://user-images.githubusercontent.com/43318877/47673796-aef37b00-dbc6-11e8-9de2-3e354a68753f.png)

**Comment by wldmr-key** [comment]
мне пока кажется, что идея убрать номера не очень перспективна в плане поиска. Вообще-то номера наложены бездарно - обводка вокруг них все-равно разрушает границы. Кроме того, ты, похоже, прибил и границы районов и еще поломал границы
У меня есть парадоксальное предложение - сделать все границы не тоньше, а толще, добившись того, чтобы все контуры на ПКК были бы замкнуты. Тогда, если точка принадлежит кадастровому участку, то он будет обнаружен и закрашен, а, если нет, то будет закрашена только замкнутая область (гарантированно - не участок).

Возможно, это и было твоим предложением, не до конца понятым мной ))

**Comment by Lakovshchikov** [comment]
@wldmr-key толще границы делать нельзя, могут скрыться мелкие участки. Я тут попробовал закрасить вообще номера, по моему получилось неплохо, если учесть, что проход идет слева сверху. Правда есть места, где в номере черные пиксели есть, внутри крупных букв. Думаю как нибудь закрасить их, что бы меньше запросов делать. 
Большие закрашенные места - это в основном объекты капитального строительства. Пока их определять не будем, но этого и в ТЗ нет.
![img12](https://user-images.githubusercontent.com/43318877/47709284-f74f7f00-dc40-11e8-9ba2-69fa4718ed81.png)

**Comment by wldmr-key** [comment]
класс! На мелкие области внутри букв, думаю, внимание обращать не стоит - если размер области, скажем меньше 2-3 пикселей в длину и в ширину, то это - не участок и обращать внимание на него не стоит (закрасить автоматом) - надеюсь, ты не позволишь пользователю оперировать с масштабом, где участок влезает в 2 пиксела

**Comment by Lakovshchikov** [comment]
@wldmr-key ну вот я тоже думал не брать мелкие области, но могут быть последствия. На большом масштабе 1px может быть равен 10-20 метрам. Надо потестить будет.

**Comment by Lakovshchikov** [comment]
@wldmr-key Я доделал алгоритм, и он даже работает. Но только с определенным масштабом. Очень странно. Вот код метода:
![image](https://user-images.githubusercontent.com/43318877/47874168-24a85280-de24-11e8-8411-e7e026f08ca4.png)
Кратное описание:
Строчка 186 - получаю черную точку на обработанной картинке (с ПКК, СЗЗ, и участком). Если черной точки нет - верну точку с отрицательными координатами.
Строчки 189, 190 - координаты точки, для запросов
Строчка 193 - Первый запрос, узнаю есть ли участок в точке, если есть - возвращаю объект с кадастровым номером участка. Если участка нет - null;
Строчка 194 - Второй запрос, если участок есть, получаю информацию о нем, если нет - null.
Метод Fill() - Закрашивает область картинки.

При относительно большом масштабе все работает, и я получаю List с кадастровыми номерами участков. Если масштаб увеличиваю, отладка прекращается, приложение закрывается, вылезет следующее:
_Вызвано исключение: "System.NullReferenceException" в Doss.exe
Вызвано исключение: "System.NullReferenceException" в Doss.exe
Вызвано исключение: "System.NullReferenceException" в Doss.exe
Вызвано исключение: "System.NullReferenceException" в Doss.exe
Программа "[13040] Doss.vshost.exe" завершилась с кодом -1 (0xffffffff)._

Вот метод Fill():
![image](https://user-images.githubusercontent.com/43318877/47874718-9a60ee00-de25-11e8-8bd0-b918fa8774c3.png)

Я для тестирования запустил алгоритм без получения картинок участка. Просто заливка области. Переделаю завтра с картинками, мб что и поменяется. При масштабе как на картинке ниже все работает, при приближении - ошибка. Расчет такого несложного участка занял около 3 секунд, и картинка закрасилась за 14 шагов.
![image](https://user-images.githubusercontent.com/43318877/47874974-502c3c80-de26-11e8-983b-fa18957e00a7.png)

**Comment by wldmr-key** [comment]
Класс!
насчет падения - есть подозрения, что ты попадаешь при заливке в щель между участками

**Comment by Lakovshchikov** [comment]
@wldmr-key не особо понимаю что за щель. На поиск участков у меня попадает изображение такого плана
![whitearoundborder](https://user-images.githubusercontent.com/43318877/47875721-4f94a580-de28-11e8-862d-7635de909fea.png)

Это промежуточная стадия:

![movepkktoplace](https://user-images.githubusercontent.com/43318877/47875733-58857700-de28-11e8-9f52-663b74d5a868.png)

Участок другой, но это просто пример, для понимания. Не понимаю что за щель?:)

**Comment by wldmr-key** [comment]
ок. Вторая гипотеза - ты забил стек рекурсией на Fill. Разверни рекурсию в циклы

**Comment by Lakovshchikov** [comment]
@wldmr-key понял, кажется видел другой алгоритм, без рекурсии. Попробую его слелать

**Comment by wldmr-key** [comment]
https://habr.com/post/116374/

**Comment by Lakovshchikov** [comment]
@wldmr-key да-да, это я и делал. Первый метод. Попробую со вторым

**Comment by wldmr-key** [comment]
более круто - в референсе по статье - https://www.codeproject.com/Articles/6017/QuickFill-An-Efficient-Flood-Fill-Algorithm но, думаю, тебе и линейного хватит

**Comment by Lakovshchikov** [comment]
@wldmr-key переделываю заливку. Переписал построчный с рекурсией метод, из более подробной (последней) ссылке. Он не совсем хорошо работает, оставляет маленькие незакрашенные места в самом низу. Да и один пиксель сверху не закрашивается:
![beforefill](https://user-images.githubusercontent.com/43318877/47928999-ddc86480-ded8-11e8-869a-480ee97a9dd6.png)
![afterfill](https://user-images.githubusercontent.com/43318877/47929005-df922800-ded8-11e8-9a54-5d81f53d6440.png)
Вот мой код, копипаст с сайта, с поправками на шарп:

```
void LineFill(int x1, int x2, int y, int nMinY, int nMaxY, int nMinX, int nMaxX)
        {
            int xL, xR;
            if (y < nMinY || nMaxY < y)
                return;
            for (xL = x1; xL >= nMinX; --xL)
            { // scan left
                if (_ImageForFill.Data[y, xL, 0] != 0)
                    break;
                _ImageForFill.Data[y, xL, 0] = 255;
            }
            if (xL < x1)
            {
                LineFill(xL, x1, y - 1, nMinY, nMaxY, nMinX, nMaxX); // fill child
                LineFill(xL, x1, y + 1, nMinY, nMaxY, nMinX, nMaxX); // fill child
                ++x1;
            }
            for (xR = x2; xR <= nMaxX; ++xR)
            { // scan right
                if (_ImageForFill.Data[y, xR, 0] != 0)
                    break;
                _ImageForFill.Data[y, xR, 0] = 255;
            }
            if (xR > x2)
            {
                LineFill(x2, xR, y - 1, nMinY, nMaxY, nMinX, nMaxX); // fill child
                LineFill(x2, xR, y + 1, nMinY, nMaxY, nMinX, nMaxX); // fill child
                --x2;
            }
            for (xR = x1; xR <= x2 && xR <= nMaxX; ++xR)
            {  // scan between
                if (_ImageForFill.Data[y, xR, 0] == 0)
                    _ImageForFill.Data[y, xR, 0] = 255;
                else
                {
                    if (x1 < xR)
                    {
                        // fill child
                        LineFill(x1, xR - 1, y - 1, nMinY, nMaxY, nMinX, nMaxX);
                        // fill child
                        LineFill(x1, xR - 1, y + 1, nMinY, nMaxY, nMinX, nMaxX);
                        x1 = xR;
                    }
                    // Note: This function still works if this step is removed.
                    for (; xR <= x2 && xR <= nMaxX; ++xR)
                    { // skip over border
                        if (_ImageForFill.Data[y, xR, 0] == 0)
                        {
                            x1 = xR--;
                            break;
                        }
                    }
                }
            }
        }

```
Разобраться не получилось, почему так. Но попробовал потестить в основном проекте. Шагов больше в 4 раза, из-за того что плохо красит, но работает при более близком масштабе. Медленно, но работает. Решил попробовать реализовать метод закраски построчный, без рекурсии, с того же сайта, но возникли вопросы. Что это:
```
typedef struct { int x1, x2, y, dy; } LINESEGMENT;

#define MAXDEPTH 10000

#define PUSH(XL, XR, Y, DY) \
    if( sp < stack+MAXDEPTH && Y+(DY) >= nMinX && Y+(DY) <= nMaxY ) \
    { sp->xl = XL; sp->xr = XR; sp->y = Y; sp->dy = DY; ++sp; }

#define POP(XL, XR, Y, DY) \
    { --sp; XL = sp->xl; XR = sp->xr; Y = sp->y+(DY = sp->dy); }
```
#define - это как я понял константа, с MAXDEPTH вроде вопросов нет. Это размер стека, как я понял.
Тогда как работает Push и Pop?
Там есть и логика, и расчеты. С константой ничего не вяжется в голове.
Вызывают их как методы, в шарпе, вроде
```
PUSH(x, x, y, 1);        /* needed in some cases */
    PUSH(x, x, y+1, -1);    /* seed segment (popped 1st) */
```
Еще касательно структуры LINESEGMENT.
Это же как в шарпе? Тогда что с ней делают?
`LINESEGMENT stack[MAXDEPTH], *sp = stack;`
Что за переменная *sp? Она же объявлена вне этого метода.
Еще есть:
`SKIP:        for( ++x; x <= x2 && GetPixel(x, y) != old_color; ++x ) {;}`
Что за SKIP? Аналог continue?

Помогите разобраться с плюсами, и если можно, хоть в кратце, расскажите про аналоги в шарпе.
Еще нашел такое:
http://unity3dmc.blogspot.com/2017/02/ultimate-3d-floodfill-scanline.html?m=1
Пока не разбирался, посмотрю что получится

**Comment by wldmr-key** [comment]
С твоим кодом разбираться не буду - сам, сам, все сам. А про плюсы расскажу
struct - ты прав, это структура
#define - это макрос - всякий раз как в тексте он встречается происходит подстановка (из экономии - чтобы не писать вызов функции). 
Фактически приведенный тобой код - это работа со стеком, который организован в массиве структур - LINESEGMENT stack[MAXDEPTH].  sp - это указатель на текущую вершину стека (*sp = stack - это ее инициализация на дне стека). sp всегда показывает на еще пустую структуру LINESEGMENT. sp++ поднимает указатель на одну позицию вверх, sp-- опускает. sp->x1 - значение x1 в структуре, на которую показывает sp.
SKIP: - это метка, на которую где-то определен goto
То есть код тут бесхитростен и миллионом способов переписывается на шарп

**Comment by Lakovshchikov** [comment]
@wldmr-key в общем я написал свой рекурсивный алгоритм, основанный на рекурсивном по линиям. Для закрашивания одинаковой области требуется в 2 раза меньше вызовов по сравнению с закраской попиксельно. При больших масштабах не падает, и это главное. И теперь я думаю, а стоит ли получать картинки участков? Это же лишние запросы, время на загрузку, возможные ошибки от сервера, лишняя работа, еще не факт что пиксели встанут идеально на свое место и не будет пустых мест между картинкой участка и границей с ПКК. У меня в теме звучит "объектов капитального строительства". Но по факту этот анализ нужен, только для промышленных объектов и специальных сооружений (свалок например), так как у других объектов нет СЗЗ. Также, они не располагаются на землях населенных пунктов. А значит ПКК выглядит не так нагружено. Не проще ли их просто закрашивать?
К примеру на такой картинке алгоритм нашел все участки за 23 итерации. А участков 14.
![image](https://user-images.githubusercontent.com/43318877/47964483-e2f9f080-e04b-11e8-9d23-2e28e8b56479.png)

**Comment by wldmr-key** [comment]
возможно, ты прав. Хотя, в отчет по работе его вполне можно включить

**Comment by Lakovshchikov** [comment]
@wldmr-key включить мой алгоритм? Или реализовать алгоритм с учётом картинок ЗУ и сравнить быстродействие?

**Comment by wldmr-key** [comment]
я предполагал только алгоритм и твой умозрительный анализ, почему ты его отверг
