### ISSUE TITLE
Обоснование выбора инструментов и платформы разработки

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#15]
@wldmr-key [Обоснование выбора инструментов и платформы разработки](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9E%D0%B1%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%B2%D1%8B%D0%B1%D0%BE%D1%80%D0%B0%20%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2%20%D0%B8%20%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D1%8B%20%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8.docx)

**Comment by wldmr-key** [comment]
я бы предложил включить в текст то, о чем мы говорили: приложение трактуется как прототип веб-разработки, поэтому хотелось бы отладить интерфейсные и алгоритмические решения. Можешь рассказать про выявленные проблемы api и их решения

**Comment by Lakovshchikov** [comment]
@wldmr-key ну да,  я постараюсь за декабрь-январь перенести его в веб. Но это будет экспепемет, и зависимости от его результата итоговая работа будет в веб или дестктоп

**Comment by Lakovshchikov** [comment]
@wldmr-key  [Обоснование выбора инструментов и платформы разработки.docx](https://github.com/Lakovshchikov/DoSS/files/2557666/default.docx)
Добавил немного в начале, выделил красным. Особых проблем я не могу выделить, они все возникают из-за моего незнания шарпа или библиотеки аркгис.

**Comment by wldmr-key** [comment]
нормально Посмотри внимательно - как правильно - "Можеть являт**ь**ся" или "может, является" (а, может, и не является)
