### ISSUE TITLE
Разработка алгоритмов обработки информации

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#16]
@wldmr-key  [Алгоритмы.docx](https://github.com/Lakovshchikov/DoSS/files/2557736/default.docx)
Нужен ли тут "Алгоритм отображения изображения на рабочей области"? Или это лучше перенести в "Разработка архитектуры приложения"? И касательно архитектуры, если я в этом пункте расскажу про работу с библиотекой arcgis и emgu cv, расскажу о преимуществах работы с ними это будет нормально? Так же могу рассказать как осуществляется формирование отчета в word

**Comment by wldmr-key** [comment]
Все достаточно мило. В архитектуре алгоритму, думаю, не место. Что касается архитектуры, то в начале имеет смысл определить основные компоненты (wpf) и подробно рассказать про левые.
Чисто стилистически - вместо "Формируется запрос, состоящий из ряда параметров таких как" правильнее сказать "Формируется HTTP GET запрос, содержащий параметры:"
