### ISSUE TITLE
Асинхронная работа

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#17]
@wldmr-key  Работа по анализу СЗЗ начинается в данном методе. Он вызывается при нажатии на кнопку анализ. Строки 603-607 скачивают картинку ПКК в данном районе. На строке 608 вызывается метод для получения, обработки и анализа СЗЗ. Строки 609-612 просто формируют строку со всеми номерами кадастровых участков, для отображения в форме.
![image](https://user-images.githubusercontent.com/43318877/48365352-bf721e00-e6bb-11e8-9b46-2b3df502a28a.png)

 MakeImageForReseach(). 180 и 181 - получают скаченное изображение ПКК, 182 - возвращает изображение для анализа.  ReseachImage() - метод анализа изображения.

![image](https://user-images.githubusercontent.com/43318877/48365467-11b33f00-e6bc-11e8-98bf-3611576f5ae4.png)

ReseachImage().  Поиск черной точки на изображении, запрос к росреестру в этой точке, формирование результирующего листа мест. Самый долговыполняемый метод

![image](https://user-images.githubusercontent.com/43318877/48365615-72db1280-e6bc-11e8-8a50-7dfdccc77298.png)

Если вдруг вам захочется посмотреть весь код, ReseachBorderThread() - в классе MainVM, MakeImageForReseach() и ReseachImage() в MapVM. Я только боюсь, что из-за связанности классов, моего "стиля" программирования, костылей и отхода от MVVM вам будет тяжело разобраться в моем коде. В ветке master сейчас актуальная версия.

**Comment by wldmr-key** [comment]
Что ты мучаешься с этими тредами?! Сам же признаешь, что они создают тебе проблемы с контекстом. Я думал ты совсем не в теме async/await, но посмотрел на код и увидел, что ты их используешь
Так что и не заморачивайся - пиши, как рекомендует микрософт https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/concepts/async/; дотнет сам управляется с потоками получше тебя, а так - ты сохраняешь полный контроль над контекстом и над возвращением из асинхронной задачи
