### ISSUE TITLE
Разработка пользовательского интерфейса

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#18]
@wldmr-key [Разработка пользовательского интерфейса](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%A0%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%B0.docx)

**Comment by wldmr-key** [comment]
вполне
