### ISSUE TITLE
Описание предметной области

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#2]
[Описание предметной области](https://github.com/Lakovshchikov/DoSS/raw/master/Doss/Doss/Docs/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%BD%D0%BE%D0%B9%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D0%B8.docx)То что в рамке из красных слешей может поменяться на то, что находится на 3 странице. Или можно как то совместить при необходимости.

**Comment by wldmr-key** [comment]
начало хорошее, но, надеюсь, дальше будет освещен вопрос, в чем заключается предпроектная проработка

**Comment by Lakovshchikov** [comment]
@wldmr-key [Описание предметной области v.2](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%BD%D0%BE%D0%B9%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D0%B8%20V2.docx)

**Comment by wldmr-key** [comment]
уже лучше, но не хватает драмы: в чем проблемы предпроектной подготовки в отсутствие твоей системы? В какой трагичной ситуации находятся предпроектные подготовщики? Какие трудности они преодолевают, которые ты в последующих главах с легкостью разрешишь?

**Comment by Lakovshchikov** [comment]
@wldmr-key [Описание предметной области v.3](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%BD%D0%BE%D0%B9%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D0%B8%20V3.docx)
Новое начинается со второй страницы, последний абзац.
