### ISSUE TITLE
Архитектура приложения

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#20]
@wldmr-key сел писать эту главу. Решил поискать что нибудь на эту тему и наткнулся на данную статью: https://habr.com/post/276593/
Прочитав, я понял что мое творение не обладает никакими свойствами, описанными в статье и рассказать мне нечего. В следствии чего возник вопрос: я должен в главе описать то, что получилось по факту? Или можно описать "эталон", к которому я должен стремится? 
Если можно описать эталон, то вижу примерно такое содержание - шаблон MVVM, разделить на смысловые блоки, модули нарисовать ко всему этому диаграммы, рассказать про паттерны Наблюдатель и singleton. Наблюдатель как я понимаю реализуется через свойства зависимости, а singleton для обработки изображения.
Если нужно описать то, что получилось по факту, тогда следующее содержание-
MVVM и мой отход от его принципов. Обосновать отход там, что это всего лишь тест функционала для будущего веба. Мб еще про механизм команд рассказать.
Надо было разбираться с архитектурой до того как сел писать код, это я уже понял.

**Comment by wldmr-key** [comment]
> Надо было разбираться с архитектурой до того как сел писать код, это я уже понял.

Еще ни один человек в мире не понимал этого до того, как садился писать свой первый нетривиальный код. :)

Твоя ссылка вполне хороша, все, что упоминается в статье, бесспорно, следует знать. Что касается практики применения, то применимо далеко не все и не всегда.

Я считаю, что ты должен описать в РПЗ то, что получилось по факту. Можно не обосновывать отход от принципов - так получилось. Переделку архитектуры (рефакторинг) можно описать как одну из грядущих задач, тем более, если ты продемонстрируешь, что представляешь как это будет делаться.

**Comment by Lakovshchikov** [comment]
@wldmr-key все что было в _"Обоснование выбора инструментов и платформы разработки"_  про MVVM  я выкинул. Оставил только упоминание о его использовании.
[Архитектура.docx](https://github.com/Lakovshchikov/DoSS/files/2592652/default.docx)

**Comment by wldmr-key** [comment]
нормально
