### ISSUE TITLE
Задачи, подлежащие решению...(НИР)

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#21]
@wldmr-key Что касается содержания этой главы. Можно ли сюда вынести все проблемы, с которыми я столкнулся (асинхронность, производительность)? Или лучше для этого выделить где-нибудь в отдельную главу? А вообще я думал выделить вопросы реализации основных функций, алгоритмов и сослаться на НИР. Вкратце описать его суть и проблемы, которые он выделяет.

**Comment by wldmr-key** [comment]
не факт, что сюда имеет смысл включать проблемы. Ты же не исследуешь их решения. Скорее они имеют отношение к технологии разработки и проектирования (сюда же твои архитектурные изыскания) - так что скорее их место в соответствующих курсовых

В части, которая начинается с "А вообще я думал" понятны только первые четыре слова :)

**Comment by Lakovshchikov** [comment]
@wldmr-key что-то похожее на 
[Перечень задач, подлежащих решению в процессе разработки.docx](https://github.com/Lakovshchikov/DoSS/files/2592624/default.docx)

**Comment by wldmr-key** [comment]
ну да, похоже. Только поподробнее расписать суть задач, я думаю
