### ISSUE TITLE
Презентация

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#23]
@wldmr-key  [КР х2 + нир Лаковщиков.pptx](https://github.com/Lakovshchikov/DoSS/files/2660542/2.%2B.pptx)

**Comment by wldmr-key** [comment]
формулировка цели НИР жутковата, как с точки зрения русского языка, так и понимания цели
слайд 3 в критериях и ограничениях последними пунктами поставь многоточия...
А так все классно - по времени должен уложиться
