### ISSUE TITLE
Эскиз пользовательского интерфейса

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#4]
[Описание работы UI](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20UI.docx). Своровал у ArcGis. Эскиз внутри файла.

**Comment by wldmr-key** [comment]
ну ты бы еще глобус нарисовал! взял бы, уж, более подходящий для реального планирования масштаб...

**Comment by Lakovshchikov** [comment]
@wldmr-key Сделал макет в WPF. Вот [новый вариант](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20UI%20alpha%20(0.1).docx).
Самому не особо нравится то, как выглядит описание земельного участка, да и пару полей надо добавить. Но это только эскиз
