### ISSUE TITLE
Концептуальная схема данных

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#5]
Попробовал составить [концептуальную схему](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9A%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%20%D1%81%D1%85%D0%B5%D0%BC%D0%B0%20v.1.png). Вот что меня смущает:
Связь "Отчет"-"Земельный участок". Отчет формируется для одного земельного участка.  Но знает он обо всех участках, которые входят в СЗЗ. Хочется связь многие ко многим, но такого делать нельзя, я помню. Хотя, я еще не особо понимаю, что я буду хранить в бд, и нужна ли она мне. Максимум что можно, это отчеты, можно по частям. Ну или предустановки для рабочей области.

**Comment by wldmr-key** [comment]
плохо помнишь. На концептуальной схеме можно все...
Нужность БД я сразу после твоих юзкейсов поставил под сомнение. Но... Пусть будет.
Кстати, я тебя уже задавал вопрос, как пользователь будет сравнивать разные варианты и получил ответ - "вручную". Это вполне нормальная тема и для расширения БД, и для НИРС на следующий семестр
