### ISSUE TITLE
IDEF0. Оформление формализованного описания процессов и поведения

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#6]
Вот что получилось. [1](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/IDEF0%20%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C%20%D0%B2%D0%B5%D1%80%D1%85%D0%BD%D0%B5%D0%B3%D0%BE%20%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D1%8F.png) и [2](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/IDEF0%20%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C%20%D0%BD%D0%B8%D0%B6%D0%BD%D0%B5%D0%B3%D0%BE%20%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D1%8F.png) .Расписал только для "Размещения объекта". ПЗЗ и Ген. план. добавил с расчетом на будущее. Или удалить их вообще? В подробной схеме пихнул их в отчет, но наверное более уместны были бы на стадии "Формирование рабочей области". Про возможность сохранения и загрузки рабочей области нигде не говорил, нужно? Это в принципе можно запихнуть в "Формирование рабочей области", ну загрузку точно. Только не знаю как вариативность на этой диаграмме показать, если надо - погуглю, сделаю.

Что касается вариаций с СЗЗ. Там вообще поступают хитро на практике. Объект сажают на участок. Двигают внутри участка. Потом, при необходимости, предлагают сделать раздел большого участка так, чтобы в результате сократилась СЗЗ. Нам это не нужно. Вот [рисунок](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Samples/Images/VGIT2igAS5I.jpg) показывающий то, что я описал выше. Красное - это начальный участок и его СЗЗ. То, что нужно сделать в моем курсаче. Синее - предложение к разделу, благодаря которому СЗЗ не проходит через земли населенного пункта, к примеру.

**Comment by wldmr-key** [comment]
ЗАМЕЧАНИЯ ПО ФУНКЦИОНАЛЬНОЙ СХЕМЕ
Схема 1
Обращаю внимание, что здесь выбора вариантов нет. Как я понимаю, здесь анализируется единственный земельный участок. Поэтому, вряд ли это полная проработка...
Что за загадочное управление "поставленная задача"?
Границы СЗЗ - если они есть, зачем СанПиН? Может, тип или характеристика объекта?

Схема 2. 

На выбор рабочей области текущий земельный участок не влияет? Можно выбирать область на антарктиде? 
Блок "выбрать участок на области" вообще непонятен. Разве этот выбор не детерминирован входом?
Итого, первые два блока я бы объединил в один

А, если, уж, тебе так дорого количество блоков, то самым первым я бы поставил извлечение полной информации об участке. Механизм - кадастровая карта, выходы - координатная информация для формирования рабочей области и атрибутная информация, которая пойдет в отчет.

Следующий блок я бы назвал не "отобразить", а "рассчитать" - это правильнее, расчет будет сделан независимо от выбранной рабочей области (я надеюсь). И выходом у него будет не участок, а участки.

Последний блок я бы назвал не "сформировать", а "оценить", предполагая, что (ты прав) пользователь захочет наложить дополнительные слои и добавить свою информацию в отчет. 

> Про возможность сохранения и загрузки рабочей области нигде не говорил, нужно?

нет, к основной функции это отношения не имеет

**Comment by Lakovshchikov** [comment]
@wldmr-key Вариант 2. [1](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/IDEF0%20%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C%20%D0%B2%D0%B5%D1%80%D1%85%D0%BD%D0%B5%D0%B3%D0%BE%20%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D1%8F%20v.2.png) [2](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/IDEF0%20%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C%20%D0%BD%D0%B8%D0%B6%D0%BD%D0%B5%D0%B3%D0%BE%20%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D1%8F%20v.2.png) .
Уменьшил количество блоков. Убрал Границы СЗЗ на входе, оставил только санпин. Тип объекта вынес на верх, так как мне кажется он накладывает ряд ограничений, да и не всегда известно изначально какой объект будет строиться. Бывает и такой вопрос: "А что вообще можно построить на этом участке?". Выбор вариантов я не добавлял. В рамках курсача я могу не успеть сделать еще и аналаз нескольких участков, надо НИР сначала хотя бы написать. Вроде все замечания учел.

**Comment by wldmr-key** [comment]
не соглашусь с расположением "тип объекта" - это точно не управление, ведь этого объекта еще не существует! Это, скорее всего, вход, ну или механизм

Я писал

> А, если, уж, тебе так дорого количество блоков, то самым первым я бы поставил извлечение полной информации об участке. Механизм - кадастровая карта, выходы - координатная информация для формирования рабочей области и атрибутная информация, которая пойдет в отчет.

Блок не обязателен, а выход - атрибутная информация, думается неплохо было бы нарисовать. впрочем, тебе виднее

**Comment by Lakovshchikov** [comment]
@wldmr-key "тип объекта" убрал. все что я подразумевал под этим описано в санпине. Добавил "извлечь информацию", теперь не знаю куда деть "земельный участок", в первый или второй блок. Хочу в оба. А ведь порядок наших блоков это же приоритетность задач, их важность, а не порядок выполнения, верно? [1](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/IDEF0%20%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C%20%D0%B2%D0%B5%D1%80%D1%85%D0%BD%D0%B5%D0%B3%D0%BE%20%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D1%8F%20v.3.png) , [2](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/IDEF0%20%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C%20%D0%BD%D0%B8%D0%B6%D0%BD%D0%B5%D0%B3%D0%BE%20%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D1%8F%20v.3.png)

**Comment by wldmr-key** [comment]
конечно-же зенмельный участок - это вход для первого блока. второй блок я бы назвал - определение рабочей области. а так уже все вполне мило
