### ISSUE TITLE
Исследовательская часть (НИР)

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#7]
Примерная тема:"Ключевые оценочные факторы, влияющие на выбор земельного участка". Первый набросок представлю до конца следующей недели.

**Comment by Lakovshchikov** [comment]
[Вот](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9D%D0%98%D0%A0.docx) что получилось на данный момент. Про веса ничего пока не писал, только критерии и обоснование. Из основных критериев - это все. Уникальность пока хромает, 46%. Это из-за первой страницы, перепишу ее.

**Comment by wldmr-key** [comment]
ну че, нормально. Правда, в зависимости от категории объекта могут появиться и дополнительные критерии - для туристического одни, для свинарника - другие

**Comment by Lakovshchikov** [comment]
@wldmr-key Новая версия [НИР](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/%D0%9D%D0%98%D0%A0%20v2.docx). Концовки нет пока. Смущает мой подход к расстановке приоритетов и вообще расчетам. Но по другому пока не представляю как. Если нужно могу еще рассказать про критерии, с точки зрения архитектуры, но мне кажется и так много получилось. Оригинальность около 70%. Это из-за первых 1-2 страниц. Перепишу их, и будет норм.

**Comment by wldmr-key** [comment]
по существу - приемлемо, но для исследования не хватает обзора альтернатив и акцентированного обоснования именно линейной свертки (как вариант, посмотреть, как это делается в литературе, на которую ты обязательно сошлешься)

**Comment by Lakovshchikov** [comment]
@wldmr-key альтернативных вариантов оценивания критериев?

**Comment by wldmr-key** [comment]
ну да, ведь, наверняка, человечество придумало что-то еще помимо линейной свертки

**Comment by Lakovshchikov** [comment]
@wldmr-key 
[НИР v3.docx](https://github.com/Lakovshchikov/DoSS/files/2580139/v2.docx)
Хоть в том направлении поправил? Или бред написал? Новое - красным

**Comment by wldmr-key** [comment]
да, вполне нормально. Если бы рассмотрел в качестве альтернативы оптимальность по Парето, было бы совсем хорошо

**Comment by Lakovshchikov** [comment]
@wldmr-key попробовал описать оптимальность по Парето. Если честно, не особо понял что по итогу меняется. Только подход к доказательству обоснованности действий?
[НИР v4.docx](https://github.com/Lakovshchikov/DoSS/files/2592783/v4.docx)

**Comment by wldmr-key** [comment]
не очень убедительно. Ведь, у тебя даже нет определения оптимальности по Парето

**Comment by Lakovshchikov** [comment]
@wldmr-key 
[НИР v5.docx](https://github.com/Lakovshchikov/DoSS/files/2603413/v5.docx)
В предложении, написанном синим цветом, я очень сомневаюсь. В конце документа про нормализацию значению написал.

**Comment by wldmr-key** [comment]
ты специально не разбиваешь текст на смысловые части? По ночам это читать невозможно! Я чуть не заснул два раза!
1. Не следует путать критерии и ограничения. СЗЗ - это ограничение. Необходимость определенных видов инженерных сетей - это ограничение. Цена - критерий. Время - критерий. 
Если бы ты честно разбил текст на разделы ив конце первой главы подвел итог, то у тебя был бы конкретный список критериев и ограничений, с примечанием, что пользователь может добавить и свои.
2. Отсюда вторая проблема. Ты пишешь при анализе "Множество возможных вариантов выбора Y является выпуклым, так как все критерии независимы друг от друга". Да ну? Стоимость не зависит от сроков? Стоимость не зависит от радиоактивности? Так что ты абсолютно прав, сомневаясь в справедливости синего предложения...
3. В формуле для альфа-И ты просто накосил. Это полнейший сюр и не лезет ни в какие ворота. Скорее всего ты имел в виду что-то другое
4.

> После того, как были установлены значения критериев и произведена расстановка коэффициентов приоритетности выполняется переоценка значений fi(y) путем сравнения существующих значений критериев конкурирующих вариантов земельных участков. Значение fi(y) будет равно 1 для критерия fi земельного участка с наибольшим значением, 0 – с меньшим значением.

Здесь лучше для нового значения использовать эф-штрих - чтобы не путать читателя. Выражаясь высоко - это называется регуляризацией коэффициентов - благодаря ей ты избавляешься от необходимости сравнивать разные размерности.

> метод является упрощенным представлением линейной свертки

Он ни разу не упрощенный и не линейный. Лучше это убери и сформулируй как -то по другому. Типа "адаптацией метода линейной свертки к требованиям заказчика". Требование интерпретируется, чтобы было доступное объяснение без калькулятора.

"Классическая линейная свертка" - тоже лучше использовать штрих для обозначения новых критериев

**Comment by Lakovshchikov** [comment]
@wldmr-key, 
[НИР v6.docx](https://github.com/Lakovshchikov/DoSS/files/2643294/v6.docx)

**Comment by wldmr-key** [comment]
пойдет. Оформляй, как следует: введение-заключение-литература
Главное, сам в терминах не запутайся ))
