### ISSUE TITLE
Проектно-конструкторская часть. Разработка структуры программной системы

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#8]
Почитав методичку я понял, что одной IDEF0-диаграммой не обойдется. Наверное надо сделать еще DFD. Есть смысл делать IDEF3? Это же (как я понял) просто более подробная и усовершенствованная IDEF0? Как я вижу этот раздел:
1) Небольшое введение, перечисляющее бизнес-процессы и действия системы.
2) IDEF0-диаграмма с описанием и обоснованием(?) всего что я там решил указать.
3) DFD-диаграмма с описанием и обоснованием(?) всего что я там решил указать.
4) Заключение о модульном составе, основных объектах и связях между ними.
На ваш взгляд этого будет достаточно?

**Comment by wldmr-key** [comment]
возможно, я плохо написал методичку. Я не имел это в виду. Все что ты перечислил имеет смысл только если ты, добавляя, скажем DFD, сообщаешь (иллюстрируешь) что-то новое
Все что ты написал, более чем достаточно

**Comment by Lakovshchikov** [comment]
[Оформил все](https://github.com/Lakovshchikov/DoSS/blob/master/Doss/Doss/Docs/3.1%20%D0%A0%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0%20%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D1%8B%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BD%D0%BE%D0%B9%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B.docx). Нужно пытаться обосновывать почему именно так расположены входы/выходы/методы, а не иначе?
