### ISSUE TITLE
РПЗ

### ISSUE THREAD

**Issue by Lakovshchikov** [Lakovshchikov/DoSS#9]
Список всех пунктов, наличие которых я предполагаю в своей РПЗ. Галочка означает, что материал для данного пункта имеется (хотя бы неоформленный).

- [x] 1. Техническое задание
- [x]  2. Исследовательская часть
    - [x]  2.1 Постановка задачи проектирования
    - [x] 2.2 Описание предметной области
    - [x] 2.3 Анализ аналогов
    - [x] 2.4 Перечень задач, подлежащих решению в процессе разработки (НИР)
    - [x] 2.5 Обоснование выбора инструментов и платформы разработки
- [x] 3. Проектно-конструкторская часть
    - [x] 3.1 Разработка структуры программной системы
    - [x] 3.2 Разработка алгоритмов обработки информации
    - [x] 3.3 Разработка интерфейса взаимодействия пользователя с системой
    - [x] 3.4 Разработка архитектуры приложения
    - [x] 3.5 Реализация функционирующего приложения
- [x] 4. Проектно-технологическая часть
    - [x] 4.1 Тестирование и отладка рабочей программы
    - [x] 4.2 Разработка руководства пользователя
- [x] 5. Заключение

**Comment by Lakovshchikov** [comment]
@wldmr-key Начинаю потихоньку формировать РПЗ. Распределяю материал для двух курсачей, вот что получается:
Для РПС:

**Техническое задание**
**Исследовательсткая часть**
Постановка задачи проектирования
Перечень задач, подлежащих…НИР
Обоснование выбора инструментов и платформы разработки
**Проектно-конструкторская часть**
Разработка структуры программной системы
Разработка алгоритмов обработки информации
Реализация функционирующего приложения
**Проектно-технологическая часть**
Тестирование и отладка рабочей программы
**Заключение**
**Список литературы**

По объему проблем нет, только из того что есть сейчас для РПС - 24 стр. В связи с этим Техническое задание на выполнение курсовой работы на втором листе выглядит следующим образом:  [Задание на выполнение курсовой работы.docx](https://github.com/Lakovshchikov/DoSS/files/2562325/default.docx)

В МИМАПР хочу запихнуть следующее:

**Техническое задание**
**Исследовательсткая часть**
Описание предметной области
Анализ аналогов
Пользовательские сценарии
**Проектно-конструкторская часть**
Концептуальная схема данных
Разработка архитектуры приложения
Разработка интерфейса взаимодействия  пользователя с системой
**Проектно-технологическая часть**
Разработка руководства пользователя
**Заключение
Список литературы**

Я понимаю что это не ваш предмет, но все таки хотелось бы согласовать с вами и услышать ваше мнение. Просто даже методички фактически ничем не отличаются и приходится раздирать работу. Тему обозначить как-то так: _Анализ предметной области и разработка архитектуры программной системы для предпроектной проработки размещения объектов капитального строительства_ С Федоровым ее еще обсужу, главное сейчас - это содержание РПЗ.

Оффтоп:
Я помню, что в ТЗ было написано про Ген. план. Сейчас постараюсь довести до ума основной функционал. Если успею, то как-нибудь попытаюсь наложить эти картинки, если нет - хочу выкинуть из тз. Или описать это в РПЗ аля "Возможное расширение функционала".  Отчет по анализу СЗЗ уже готов. Осталось из основного - сохранение состояния рабочей области.

**Comment by wldmr-key** [comment]
> В связи с этим Техническое задание на выполнение курсовой работы на втором листе выглядит следующим образом

знать бы как оно выглядело... На первый взгляд, ничего существенного не поменялось. Может, и не стоит заморачиваться с заменой?

По обеим структурам замечаний нет. По мимапр разве что
>Проектно-технологическая часть
Разработка руководства пользователя

ты что, реально хочешь писать руководство пользователя? Хотя, может, и не вредно...

**Comment by Lakovshchikov** [comment]
@wldmr-key Оформил [РПЗ.docx](https://github.com/Lakovshchikov/DoSS/files/2608912/default.docx).
Из того что вы вообще не видели - введение, заключение, поправленные задачи, подлежащие решению... . Оформление приложений поправлю при печати.
Тут вспомнили что нужно еще по 2 листа А1 на курсач.
На рпз можно 1 лист со скринами развертки системы, а вот второй думаю еще. Есть idef0 но это маловато для целого листа А1. Мб алгоритмы закраски там расписать?
На мимапр 1 лист на интерфейс пользовательский, второй с таблицами use case и концептуальной схемой?

**Comment by wldmr-key** [comment]
алгоритмы вполне можно. Но ты зря мельчишь. И IDEF, и use case, и концептуальная схема вполне нормально кладутся на лист каждая

**Comment by wldmr-key** [comment]
По РПЗ - 
1) прогони через спеллчекер и сам внимательно посмотри на текст - "выли поставлены " - спеллчекер не замечает. А я - да.
2) обороты типа ".Необходимо научить систему " ни к чему. Построже надо. И поконкретнее: "техническое задание накладывает ряд ограничений" - это масло масляное. "В частности в техническом отчете должны содержаться ...; он должен ..." - это да
3) по содержимому - вполне, вполне.
